import { FormEvent, useState } from "react";
import { approveTester, listTesters, preapproveTester, setTesterStatus, type TesterProfile } from "./services/api";

const statusLabel: Record<TesterProfile["status"], string> = { requested: "Aguardando análise", preapproved: "Convite emitido", active: "Ativo", rejected: "Não aprovado", suspended: "Suspenso", invite_expired: "Convite expirado" };

export default function AdminPortal({ onExit }: { onExit: () => void }) {
  const [key, setKey] = useState(() => sessionStorage.getItem("confere_admin_key") ?? "");
  const [testers, setTesters] = useState<TesterProfile[]>([]);
  const [invite, setInvite] = useState<{ email: string; code: string; expires: string } | null>(null);
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false);

  async function enter(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); try { const items = await listTesters(key); sessionStorage.setItem("confere_admin_key", key); setTesters(items); } catch (e) { setError(e instanceof Error ? e.message : "Acesso não autorizado."); } finally { setBusy(false); } }
  async function refresh() { setTesters(await listTesters(key)); }
  async function preapprove(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError(""); try { const result = await preapproveTester(key, { email: String(form.get("email")), full_name: String(form.get("full_name")) || undefined }); setInvite({ email: result.tester.email, code: result.invite_code, expires: result.expires_at }); await refresh(); event.currentTarget.reset(); } catch (e) { setError(e instanceof Error ? e.message : "Não foi possível emitir o convite."); } finally { setBusy(false); } }
  async function approve(item: TesterProfile) { setBusy(true); setError(""); try { const result = await approveTester(key, item.id); setInvite({ email: result.tester.email, code: result.invite_code, expires: result.expires_at }); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Não foi possível aprovar."); } finally { setBusy(false); } }
  async function change(item: TesterProfile, status: "active" | "rejected" | "suspended") { setBusy(true); setError(""); try { await setTesterStatus(key, item.id, status); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Não foi possível alterar o acesso."); } finally { setBusy(false); } }

  if (!testers.length && !sessionStorage.getItem("confere_admin_key")) return <main className="partner-login admin-login"><button className="back" onClick={onExit}>← Voltar</button><section><span className="eyebrow">Acesso restrito</span><h1>Administração</h1><p>Use a chave administrativa configurada no servidor.</p><form onSubmit={enter}><label>Chave administrativa<input type="password" value={key} onChange={e => setKey(e.target.value)} required /></label><button className="primary" disabled={busy}>Entrar</button></form>{error && <p className="error">{error}</p>}</section></main>;

  return <main className="partner-page admin-page"><div className="partner-toolbar"><button className="back" onClick={onExit}>← Voltar ao site</button><button onClick={() => { sessionStorage.removeItem("confere_admin_key"); setTesters([]); setKey(""); }}>Sair</button></div><div className="project-heading"><div><span className="eyebrow">Programa fechado de testes</span><h1>Usuários autorizados</h1><p>Aprove solicitações, emita convites e suspenda acessos.</p></div><strong>{testers.filter(t => t.status === "active").length} ativos</strong></div>
    {error && <p className="error">{error}</p>}{invite && <aside className="invite-result"><strong>Convite gerado para {invite.email}</strong><p>Envie este código pelo e-mail oficial. Ele aparece somente agora e expira em {new Date(invite.expires).toLocaleString("pt-BR")}.</p><code>{invite.code}</code><button onClick={() => navigator.clipboard.writeText(invite.code)}>Copiar código</button></aside>}
    <section className="admin-grid"><form className="partner-card stack-form" onSubmit={preapprove}><h2>Pré-autorizar arquiteto</h2><label>E-mail *<input name="email" type="email" required /></label><label>Nome<input name="full_name" /></label><button className="primary" disabled={busy}>Gerar convite</button></form>
      <div className="admin-list"><h2>Cadastros</h2>{testers.length === 0 ? <p className="empty-state">Nenhum cadastro ainda.</p> : testers.sort((a,b) => b.created_at.localeCompare(a.created_at)).map(item => <article key={item.id}><div><strong>{item.full_name || "Nome a completar"}</strong><a href={`mailto:${item.email}`}>{item.email}</a><small>{item.professional_role || "Perfil não informado"} · {item.city_state || "Local não informado"}</small><span className={`status-pill ${item.status}`}>{statusLabel[item.status]}</span></div><div className="admin-actions">{(item.status === "requested" || item.status === "invite_expired") && <button onClick={() => approve(item)}>Aprovar e convidar</button>}{item.status === "active" && <button onClick={() => change(item, "suspended")}>Suspender</button>}{item.status === "suspended" && <button onClick={() => change(item, "active")}>Reativar</button>}{item.status !== "rejected" && item.status !== "active" && <button onClick={() => change(item, "rejected")}>Não aprovar</button>}</div></article>)}</div>
    </section>
  </main>;
}
